import assert from 'node:assert/strict';
import { FarmModel } from '../farmstead/farm-core.mjs';

const farm = new FarmModel();
assert.equal(farm.day, 1);
assert.equal(farm.coins, 60);
assert.equal(farm.energy, 14);
assert.equal(farm.tiles.length, 30);
assert.equal(farm.act(1, 'hoe').ok, true);
assert.equal(farm.tiles[1].state, 'tilled');
assert.equal(farm.energy, 13);
assert.deepEqual(farm.act(1, 'hoe'), { ok: false, reason: 'Already tilled' });
assert.equal(farm.energy, 13);

assert.deepEqual(farm.seeds, { turnip: 6, carrot: 0, pumpkin: 0 });
assert.equal(farm.act(1, 'seed', 'turnip').ok, true);
assert.equal(farm.tiles[1].crop, 'turnip');
assert.equal(farm.seeds.turnip, 5);
assert.equal(farm.energy, 12);
assert.deepEqual(farm.act(1, 'seed', 'turnip'), { ok: false, reason: 'Plot is occupied' });
assert.equal(farm.act(1, 'water').ok, true);
assert.equal(farm.tiles[1].watered, true);
assert.equal(farm.energy, 11);
const night = farm.endDay();
assert.equal(night.day, 2);
assert.equal(farm.day, 2);
assert.equal(farm.energy, 14);
assert.equal(farm.tiles[1].ready, true);
assert.equal(farm.tiles[1].watered, false);
assert.equal(farm.act(1, 'harvest').ok, true);
assert.equal(farm.tiles[1].state, 'tilled');
assert.deepEqual(farm.produce, { turnip: 1, carrot: 0, pumpkin: 0 });
assert.equal(farm.energy, 13);
assert.deepEqual(farm.sellAll(), { ok: true, items: 1, coins: 18 });
assert.equal(farm.coins, 78);
assert.equal(farm.earnings, 18);
assert.deepEqual(farm.buySeeds('carrot', 2), { ok: true, spent: 28 });
assert.equal(farm.coins, 50);
assert.equal(farm.seeds.carrot, 2);

const questFarm = new FarmModel();
assert.deepEqual(questFarm.order, { crop: 'turnip', count: 3, reward: 35 });
questFarm.produce.turnip = 3;
assert.deepEqual(questFarm.deliverOrder(), { ok: true, reward: 35, crop: 'turnip', count: 3 });
assert.equal(questFarm.coins, 95);
assert.equal(questFarm.earnings, 35);
assert.deepEqual(questFarm.order, { crop: 'carrot', count: 2, reward: 80 });
assert.deepEqual(questFarm.deliverOrder(), { ok: false, reason: 'Need 2 carrots' });

questFarm.day = 4;
questFarm.energy = 7;
questFarm.seeds.pumpkin = 3;
const restored = FarmModel.fromSnapshot(questFarm.snapshot());
assert.equal(restored.day, 4);
assert.equal(restored.energy, 7);
assert.equal(restored.coins, 95);
assert.equal(restored.orderIndex, 1);
assert.equal(restored.seeds.pumpkin, 3);
const safe = FarmModel.fromSnapshot({ day: -99, coins: 'oops', energy: 999, tiles: [] });
assert.equal(safe.day, 1);
assert.equal(safe.coins, 60);
assert.equal(safe.energy, 14);
assert.equal(safe.tiles.length, 30);

const futureVersion = FarmModel.fromSnapshot({ version: 999, day: 77, coins: 1234, tiles: Array(30).fill({ state: 'grass' }) });
assert.equal(futureVersion.day, 1);
assert.equal(futureVersion.coins, 60);

const forgedReadyTiles = Array.from({ length: 30 }, () => ({ state: 'grass' }));
forgedReadyTiles[0] = { state: 'planted', crop: 'turnip', growth: 0, watered: true, ready: true };
const forgedReady = FarmModel.fromSnapshot({ version: 1, tiles: forgedReadyTiles });
assert.equal(forgedReady.tiles[0].ready, false);
assert.deepEqual(forgedReady.act(0, 'harvest'), { ok: false, reason: 'Not ready to harvest' });
console.log('FARMSTEAD CORE SLICE 5 PASS');
