import * as THREE from '../vendor/three.module.min.js';

const canvas=document.getElementById('game'),menu=document.getElementById('menu'),gameover=document.getElementById('gameover'),pausePanel=document.getElementById('pause'),raceComplete=document.getElementById('race-complete'),shop=document.getElementById('shop'),gallery=document.getElementById('gallery'),pauseToggle=document.getElementById('pause-toggle'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),coinsEl=document.getElementById('coins'),finalScoreEl=document.getElementById('final-score'),raceHud=document.getElementById('race-hud');
const WORLD_HALF=8,SURFACE_WIDTH=32,AHEAD=22,BEHIND=7,HOP_TIME=.16,RACE_LENGTH=50,SIM_STEP=1/60,RIVAL_STEP=.18,PLAYER_VISUAL_SCALE=.72,SAVE_KEY='roadHop.save.v2';
const palette={cream:0xfff7d6,gold:0xf7d154,purple:0x7b45da,cyan:0x55f3dd,ink:0x20113f};
const BIOMES={
 meadow:{label:'Meadow',sky:0x92e8e0,fog:0x92e8e0,grass:0x62cf79,dark:0x46ad60,road:0x50566b,light:0xfff3c4,event:'butterflies'},
 wetlands:{label:'Rainy Wetlands',sky:0x668c94,fog:0x668c94,grass:0x4f8f72,dark:0x326b62,road:0x454f5b,water:0x3188a8,light:0xb8dddf,event:'rain'},
 autumn:{label:'Autumn',sky:0xe6a868,fog:0xd88d55,grass:0xb76c3d,dark:0x86412e,road:0x55474a,light:0xffc56b,event:'falling leaves'},
 haunted:{label:'Haunted',sky:0x090612,fog:0x24113f,grass:0x38234f,dark:0x20152f,road:0x17151f,light:0xd8b9ff,event:'spectral ghosts'}
};
const CHARACTERS={PIP:{price:0,color:0x7b45da,accent:0x55f3dd,shape:'bot'},BOUNCE:{price:75,color:0xf06d91,accent:0xfff7d6,shape:'bunny'},RUSTY:{price:175,color:0xbd613c,accent:0xf7d154,shape:'tin'},BOLT:{price:300,color:0x3f94d8,accent:0xffffff,shape:'runner'},JACK:{price:500,color:0xe57424,accent:0x4d2b28,shape:'pumpkin'},WISP:{price:750,color:0x68e6d4,accent:0xdffff9,shape:'spirit'}};
const MISSIONS=['Reach 20 new rows','Cross 3 bridges','Finish a Road Rally','Score 2 near misses','Visit 2 biomes'];

function clampInt(v,min,max,fallback=0){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.floor(n))):fallback}
function dateKey(){return new Date().toISOString().slice(0,10)}
function dailySeed(key=dateKey()){let h=2166136261;for(let i=0;i<key.length;i++){h^=key.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function safeLegacyBest(){try{return clampInt(localStorage?.getItem('roadHop.best'),0,999999)}catch{return 0}}
function defaultSave(legacyBest=0){return{coins:0,best:clampInt(legacyBest,0,999999),owned:['PIP'],character:'PIP',biome:'meadow',mode:'endless',postcards:[],records:{rallyBest:0,daily:{}},missions:{day:dateKey(),progress:[0,0,0],claimed:[false,false,false],biomes:[]},visited:[]}}
function normalizeList(values,allowed,max=allowed.length){const out=[];if(!Array.isArray(values))return out;for(const value of values)if(allowed.includes(value)&&!out.includes(value)){out.push(value);if(out.length>=max)break}return out}
function validDayKey(key){if(!/^\d{4}-\d{2}-\d{2}$/.test(key))return false;const parsed=new Date(`${key}T00:00:00Z`);return Number.isFinite(parsed.getTime())&&parsed.toISOString().slice(0,10)===key}
function normalizeDaily(values){const out={};if(!values||typeof values!=='object'||Array.isArray(values))return out;const keys=Object.keys(values).filter(validDayKey).sort().slice(-90);for(const key of keys)out[key]=clampInt(values[key],0,999999);return out}
function normalizeSave(raw,legacyBest=0){const d=defaultSave(legacyBest),s=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};d.coins=clampInt(s.coins,0,999999);d.best=clampInt(s.best,0,999999,d.best);d.owned=normalizeList(s.owned,Object.keys(CHARACTERS));if(!d.owned.includes('PIP'))d.owned.unshift('PIP');d.character=d.owned.includes(s.character)?s.character:'PIP';d.biome=BIOMES[s.biome]?s.biome:'meadow';d.mode=['endless','rally'].includes(s.mode)?s.mode:'endless';const biomeKeys=Object.keys(BIOMES);d.postcards=normalizeList(s.postcards,biomeKeys);d.visited=normalizeList(s.visited,biomeKeys);if(s.records&&typeof s.records==='object'&&!Array.isArray(s.records)){d.records.rallyBest=clampInt(s.records.rallyBest,0,4);d.records.daily=normalizeDaily(s.records.daily)}if(s.missions&&typeof s.missions==='object'&&s.missions.day===dateKey()){d.missions={day:dateKey(),progress:[0,1,2].map(i=>clampInt(s.missions.progress?.[i],0,9999)),claimed:[0,1,2].map(i=>!!s.missions.claimed?.[i]),biomes:normalizeList(s.missions.biomes,biomeKeys)}}return d}
function loadSave(){const legacyBest=safeLegacyBest();try{return normalizeSave(JSON.parse(localStorage?.getItem(SAVE_KEY)||'null'),legacyBest)}catch{return defaultSave(legacyBest)}}
let uiDirty=true,uiWriteCount=0;
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));localStorage.setItem('roadHop.best',String(save.best))}catch{}uiDirty=true}
let save=loadSave();
function changeCoins(delta){const amount=Number(delta);if(!Number.isFinite(amount))return save.coins;save.coins=clampInt(save.coins+amount,0,999999,save.coins);return save.coins}

function material(color,opts={}){return new THREE.MeshLambertMaterial({color,...opts})}
function box(w,h,d,color){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color))}
function glowBox(w,h,d,color,opacity=1){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity}))}
function disposeObject(object){if(object.geometry)object.geometry.dispose();if(object.material){const ms=Array.isArray(object.material)?object.material:[object.material];for(let i=0;i<ms.length;i++)ms[i].dispose()}for(let i=0;i<object.children.length;i++)disposeObject(object.children[i])}
function seeded(row,salt=0){let x=Math.imul(row+173+salt*97+(dailyMode?dailySeed()%997:0),2654435761);x^=x>>>15;x=Math.imul(x,2246822519);return((x^(x>>>13))>>>0)/4294967296}

const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-9,9,6,-6,.1,100),cameraTarget=new THREE.Vector3(),renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.shadowMap.enabled=false;renderer.outputColorSpace=THREE.SRGBColorSpace;
const hemi=new THREE.HemisphereLight(0xffffff,0x52633d,2.25),sun=new THREE.DirectionalLight(0xfff3c4,3.5);sun.position.set(-8,16,10);scene.add(hemi,sun);
const world=new THREE.Group(),ambience=new THREE.Group(),racersGroup=new THREE.Group(),characterGroup=new THREE.Group(),skyDecor=new THREE.Group(),underlay=box(48,.2,60,BIOMES[save.biome].dark);underlay.name='world-underlay';camera.add(skyDecor);scene.add(camera,underlay,world,ambience,racersGroup,characterGroup);
function createCharacter(name,scale=1){const c=CHARACTERS[name]||CHARACTERS.PIP,g=new THREE.Group(),body=box(.72,.68,.72,c.color);body.position.y=.64;g.add(body);const head=box(.66,.45,.62,c.color);head.position.set(0,1.16,.02);g.add(head);const face=box(.48,.17,.04,c.accent);face.position.set(0,1.18,.34);g.add(face);if(c.shape==='bunny'){for(const x of[-.2,.2]){const ear=box(.15,.5,.15,c.accent);ear.position.set(x,1.68,0);g.add(ear)}}else if(c.shape==='pumpkin'){const stem=box(.12,.28,.12,0x4b783c);stem.position.y=1.55;g.add(stem)}else if(c.shape==='spirit'){body.rotation.z=Math.PI/4;body.scale.set(.8,.8,.8)}else{const antenna=box(.09,.25,.09,palette.ink);antenna.position.y=1.53;g.add(antenna);const bulb=box(.17,.17,.17,c.accent);bulb.position.y=1.7;g.add(bulb)}for(const x of[-.23,.23]){const foot=box(.23,.16,.38,c.accent);foot.position.set(x,.14,.08);g.add(foot)}g.scale.setScalar(scale);g.rotation.y=Math.PI;return g}
let pip=createCharacter(save.character,PLAYER_VISUAL_SCALE);characterGroup.add(pip);
function replaceCharacter(){characterGroup.remove(pip);disposeObject(pip);pip=createCharacter(save.character,PLAYER_VISUAL_SCALE);characterGroup.add(pip);game.pip=pip}

const lanes=[],vehicles=[];const player={row:0,x:0,moving:null};
const rivals=[{id:1,name:'MOSS',profile:'careful',row:0,x:-2,checkpoint:0,crashes:0,wait:0,finished:false},{id:2,name:'DASH',profile:'balanced',row:0,x:2,checkpoint:0,crashes:0,wait:0,finished:false},{id:3,name:'HEX',profile:'aggressive',row:0,x:4,checkpoint:0,crashes:0,wait:0,finished:false}];
const race={finished:false,order:[],reward:0,settled:false};
let state='MENU',score=0,best=save.best,furthest=0,forceCrash=false,cameraRow=3,lastTime=0,audio=null,biome=save.biome,mode=save.mode,dailyMode=false,nearMiss={lastRow:-99,count:0},ambienceTime=0,rivalClock=0,simAccumulator=0;

function laneType(row){if(row<=1||row%5===0)return'grass';if(biome==='wetlands'&&(row%4===2||seeded(row,21)<.23))return'water';return seeded(row)>.34?'road':'grass'}
function addTree(group,row,x,blockers){const b=BIOMES[biome];const trunk=box(.28,.65,.28,biome==='haunted'?0x49335f:0x805335);trunk.position.set(x,.22,-row);group.add(trunk);let leaf=biome==='autumn'?(seeded(row,x+20)>.5?0xd95632:0xe99c32):biome==='haunted'?0x161020:(seeded(row,x+20)>.5?b.dark:b.grass);const crown=box(.78,.82,.78,leaf);crown.position.set(x,.9,-row);if(biome==='haunted'){crown.name='haunted-dead-tree';crown.scale.set(.28,1.65,.28);crown.rotation.z=seeded(row,x+40)>.5?.42:-.42;const branch=box(.62,.12,.14,0x49335f);branch.position.set(x+(crown.rotation.z>0?.18:-.18),1,-row);branch.rotation.z=-crown.rotation.z;group.add(branch)}group.add(crown);blockers.add(x)}
function addProp(group,row,x){if(biome==='haunted'){const side=(x<0?-1:1)*Math.min(6.4,Math.max(5.2,Math.abs(x))),cluster=new THREE.Group();cluster.name='haunted-grave-cluster';const grave=box(.52,.62,.18,0x9385aa);grave.position.y=.28;grave.rotation.z=side<0?-.12:.12;const crossV=box(.1,.72,.1,0x5f516f),crossH=box(.4,.1,.1,0x5f516f);crossV.position.set(.62,.34,.04);crossH.position.set(.62,.48,.04);cluster.add(grave,crossV,crossH);if(seeded(row,66)>.45){const pumpkin=glowBox(.4,.34,.38,0xff7a24);pumpkin.position.set(-.55,.16,.03);cluster.add(pumpkin)}cluster.position.set(side,0,-row);group.add(cluster);const lamp=new THREE.Group();lamp.name='haunted-lamp';const pole=box(.08,1.3,.08,0x30243f),arm=box(.38,.07,.07,0x30243f),glow=glowBox(.3,.28,.3,0xb8ffef,.92);pole.position.y=.55;arm.position.set(side<0?-.15:.15,1.16,0);glow.position.set(side<0?-.3:.3,1.05,0);lamp.add(pole,arm,glow);lamp.position.set(side+(side<0?.75:-.75),0,-row);group.add(lamp)}else if(biome==='autumn'){const fence=box(.8,.34,.12,0x87512d);fence.position.set(x,.03,-row);group.add(fence);const pile=box(.7,.12,.5,seeded(row,x+73)>.5?0xd95632:0xe99c32);pile.name='autumn-leaf-pile';pile.position.set(x+1,.01,-row);pile.rotation.y=.35;group.add(pile)}else if(biome==='wetlands'){for(const dx of[-.14,.14]){const reed=box(.06,.55,.06,0x76aa53);reed.position.set(x+dx,.1,-row);reed.rotation.z=dx;group.add(reed)}}}
function createCar(row,index,direction,speed){const colors=[0xff6b58,0x45b7e8,0xf2c94c,0xe96fd1],g=new THREE.Group(),body=box(1.12,.42,.68,colors[(row+index)%4]);body.position.y=.42;g.add(body);const cabin=box(.55,.32,.58,0xd9f8ff);cabin.position.set(-direction*.08,.75,0);g.add(cabin);for(const dx of[-.36,.36])for(const dz of[-.34,.34]){const wheel=box(.19,.2,.1,0x1c1b28);wheel.position.set(dx,.24,dz);g.add(wheel)}g.position.set(-WORLD_HALF+seeded(row,index)*16,0,-row);g.rotation.y=direction<0?Math.PI:0;world.add(g);const v={mesh:g,row,x:g.position.x,direction,speed,width:1.15};vehicles.push(v);return v}
function makeLane(row){const type=laneType(row),b=BIOMES[biome],g=new THREE.Group(),blockers=new Set(),bridges=new Set();const color=type==='road'?b.road:type==='water'?b.water:(row%2?b.grass:b.dark),base=box(SURFACE_WIDTH,type==='road'?.22:.42,1,color);base.position.set(0,type==='road'?-.12:-.22,-row);g.add(base);
 if(type==='road'){for(let x=-7.4;x<8;x+=2){const mark=box(.85,.025,.055,palette.cream);mark.position.set(x,.025,-row);g.add(mark)}const direction=seeded(row,2)>.5?1:-1,speed=1.8+seeded(row,3)*1.8+Math.min(row,80)*.012,count=2+(seeded(row,4)>.5?1:0);for(let i=0;i<count;i++){const car=createCar(row,i,direction,speed);car.x=-7+i*(16/count)+seeded(row,i+9)*1.2;car.mesh.position.x=car.x}}
 else if(type==='water'){for(const x of[-1,0,1]){bridges.add(x);const tile=box(.92,.12,.96,0xb27a43);tile.position.set(x,.03,-row);g.add(tile)}for(const x of[-7,-5,5,7])addProp(g,row,x)}
 else if(row>1){const count=1+Math.floor(seeded(row,5)*3);for(let i=0;i<count;i++){let x=-6+Math.floor(seeded(row,i+12)*13);if(x===0&&row<4)x=3;while(blockers.has(x))x=Math.min(7,x+1);addTree(g,row,x,blockers)}addProp(g,row,row%2?-7:7)}
 world.add(g);const lane={row,type,group:g,blockers,bridges};lanes.push(lane);return lane}
function clearWorld(){while(world.children.length){const child=world.children[world.children.length-1];world.remove(child);disposeObject(child)}lanes.length=0;vehicles.length=0}
function ensureWorld(center){let low=center,high=center;if(mode==='rally'){const active=[player.row,...rivals.filter(r=>!r.finished).map(r=>r.row)];low=Math.min(center,...active);high=Math.max(center,...active)}const min=Math.max(-5,low-BEHIND),max=mode==='rally'?Math.min(RACE_LENGTH,high+AHEAD):center+AHEAD;for(let row=min;row<=max;row++)if(!lanes.some(l=>l.row===row))makeLane(row);for(let i=lanes.length-1;i>=0;i--)if(lanes[i].row<min||lanes[i].row>max){world.remove(lanes[i].group);disposeObject(lanes[i].group);lanes.splice(i,1)}for(let i=vehicles.length-1;i>=0;i--)if(vehicles[i].row<min||vehicles[i].row>max){world.remove(vehicles[i].mesh);disposeObject(vehicles[i].mesh);vehicles.splice(i,1)}}
function laneAt(row){return lanes.find(l=>l.row===row)}
function clearAmbience(){while(ambience.children.length){const o=ambience.children[0];ambience.remove(o);disposeObject(o)}while(skyDecor.children.length){const o=skyDecor.children[0];skyDecor.remove(o);disposeObject(o)}}
function placeSkyDecor(){const moon=skyDecor.getObjectByName('haunted-moon');if(moon){moon.position.set(camera.left+1.2,camera.top-1.6,-2);moon.scale.setScalar(Math.min(1,(camera.right-camera.left)/12))}}
function buildAmbience(){clearAmbience();if(biome==='haunted'){const moon=new THREE.Mesh(new THREE.CircleGeometry(.72,16),new THREE.MeshBasicMaterial({color:0xe7d5ff,depthTest:false,depthWrite:false,transparent:true,opacity:.62,fog:false}));moon.name='haunted-moon';moon.renderOrder=1000;skyDecor.add(moon);placeSkyDecor();for(let i=0;i<9;i++){const ghost=new THREE.Group(),body=glowBox(.42,.58,.22,i%3===0?0xc39cff:0xb8ffef,.72),head=glowBox(.34,.32,.28,0xeafffa,.82),eyeL=glowBox(.055,.065,.025,0x090612),eyeR=glowBox(.055,.065,.025,0x090612);ghost.name='haunted-ghost';body.position.y=.25;head.position.y=.7;eyeL.position.set(-.09,.73,.15);eyeR.position.set(.09,.73,.15);ghost.add(body,head,eyeL,eyeR);ghost.userData.baseX=-6+(i*3.1)%12;ghost.userData.baseY=.55+(i%3)*.42;ghost.position.set(ghost.userData.baseX,ghost.userData.baseY,-3-i*4);ambience.add(ghost)}return}const count=biome==='meadow'?8:24;for(let i=0;i<count;i++){let c=0xffe66d,w=.08,h=.08,d=.08;if(biome==='wetlands'){c=0xa9e9ff;w=.025;h=.7;d=.025}else if(biome==='autumn'){c=i%2?0xdc5434:0xf2a33a;w=.16;h=.04;d=.12}const p=box(w,h,d,c);p.material.transparent=true;p.material.opacity=.85;p.position.set(-8+(i*3.7)%16,1+(i*1.31)%8,-((i*7)%35));p.userData.base=i;ambience.add(p)}}
function applyBiome(){const b=BIOMES[biome];scene.background=new THREE.Color(b.sky);scene.fog=new THREE.Fog(b.fog,biome==='haunted'?10:20,biome==='haunted'?42:46);underlay.material.color.setHex(b.dark);sun.color.setHex(b.light);sun.intensity=biome==='haunted'?2.35:3.5;hemi.color.setHex(biome==='haunted'?0xbca6ff:0xffffff);hemi.groundColor.setHex(biome==='haunted'?0x164d4b:0x52633d);hemi.intensity=biome==='haunted'?1.75:2.25;buildAmbience()}
function updateAmbience(dt){ambienceTime+=dt;for(let i=0;i<ambience.children.length;i++){const p=ambience.children[i];if(biome==='wetlands'){p.position.y-=dt*8;if(p.position.y<0)p.position.y=9}else if(biome==='autumn'){p.position.y-=dt*.7;p.rotation.y+=dt*2;if(p.position.y<0)p.position.y=8}else if(biome==='haunted'){p.position.x=p.userData.baseX+Math.sin(ambienceTime*1.5+i)*.32;p.position.y=p.userData.baseY+Math.sin(ambienceTime*2.1+i)*.16;if(p.position.z>-cameraRow+4)p.position.z-=36;if(p.position.z<-cameraRow-34)p.position.z+=36}else p.position.y+=Math.sin(ambienceTime*2+i)*dt*.03}}

function ensureMissionDay(){const today=dateKey();if(save.missions.day===today)return false;save.missions={day:today,progress:[0,0,0],claimed:[false,false,false],biomes:[]};return true}
function activeMissions(){ensureMissionDay();const seed=dailySeed();return [0,1,2].map(i=>MISSIONS[(seed+i*2)%MISSIONS.length])}
function missionTarget(label){if(label.includes('20'))return 20;if(label.includes('3 bridges'))return 3;if(label.includes('Road Rally'))return 1;if(label.includes('2 near'))return 2;return 2}
function addMission(kind,amount=1){ensureMissionDay();const labels=activeMissions();for(let i=0;i<3;i++){const l=labels[i];if((kind==='rows'&&l.includes('new rows'))||(kind==='bridges'&&l.includes('bridges'))||(kind==='rally'&&l.includes('Rally'))||(kind==='near'&&l.includes('near'))||(kind==='biomes'&&l.includes('biomes')))save.missions.progress[i]+=amount;if(!save.missions.claimed[i]&&save.missions.progress[i]>=missionTarget(l)){save.missions.claimed[i]=true;changeCoins(25)}}persist();renderMissions()}
function renderMissions(){const rolled=ensureMissionDay(),list=document.getElementById('missions');list.replaceChildren();const labels=activeMissions();for(let i=0;i<3;i++){const li=document.createElement('li'),target=missionTarget(labels[i]);li.textContent=`${labels[i]} · ${Math.min(target,save.missions.progress[i])}/${target}${save.missions.claimed[i]?' ✓ +25':''}`;list.append(li)}document.getElementById('daily').textContent=`DAILY ${dateKey()} · seed ${dailySeed()} · best ${save.records.daily[dateKey()]||0}`;if(rolled)persist()}
function renderShop(){const root=document.getElementById('shop-cards');root.replaceChildren();for(const [name,c] of Object.entries(CHARACTERS)){const card=document.createElement('div');card.className='card';const title=document.createElement('strong');title.textContent=name;const desc=document.createElement('div'),button=document.createElement('button'),owned=save.owned.includes(name);desc.textContent=owned?(save.character===name?'SELECTED':'OWNED'):`${c.price} COINS`;button.textContent=owned?(save.character===name?'SELECTED':'SELECT'):`BUY · ${c.price}`;button.disabled=save.character===name||(!owned&&save.coins<c.price);button.addEventListener('click',()=>{if(owned)selectCharacter(name);else if(buyCharacter(name))selectCharacter(name);renderShop()});card.append(title,desc,button);root.append(card)}}
function renderGallery(){const root=document.getElementById('gallery-cards');root.replaceChildren();for(const [key,b] of Object.entries(BIOMES)){const card=document.createElement('div');card.className='card';const title=document.createElement('strong'),desc=document.createElement('div');title.textContent=b.label;desc.textContent=save.postcards.includes(key)?`POSTCARD UNLOCKED · ${b.event.toUpperCase()}`:'LOCKED · REACH ROW 10';card.append(title,desc);root.append(card)}}
function buyCharacter(name){const c=CHARACTERS[name];if(!c||save.owned.includes(name)||save.coins<c.price)return false;changeCoins(-c.price);save.owned.push(name);persist();return true}
function selectCharacter(name){if(!save.owned.includes(name))return false;save.character=name;replaceCharacter();persist();return true}
function setBiome(value){if(!BIOMES[value])return false;biome=value;save.biome=value;document.getElementById('biome-select').value=value;applyBiome();persist();return true}
function updateDailyButton(){document.getElementById('daily-toggle').textContent=dailyMode?'DAILY CHALLENGE ACTIVE':'PLAY DAILY CHALLENGE'}
function setDailyMode(value){dailyMode=!!value;if(dailyMode&&mode!=='endless'){mode='endless';save.mode='endless';document.getElementById('mode-select').value='endless'}updateDailyButton();persist();return dailyMode}
function setMode(value){if(!['endless','rally'].includes(value))return false;mode=value;save.mode=value;if(value==='rally'&&dailyMode){dailyMode=false;updateDailyButton()}document.getElementById('mode-select').value=value;persist();return true}
function updateUI(){uiWriteCount++;uiDirty=false;scoreEl.textContent=score;bestEl.textContent=best;coinsEl.textContent=save.coins;finalScoreEl.textContent=score;document.getElementById('race-row').textContent=`${Math.min(player.row,RACE_LENGTH)}/${RACE_LENGTH}`;const place=1+rivals.filter(r=>r.row>player.row).length;document.getElementById('race-place').textContent=`${place}/4`}
function setState(next){state=next;game.state=next;menu.classList.toggle('hidden',next!=='MENU');gameover.classList.toggle('hidden',next!=='GAME_OVER');pausePanel.classList.toggle('hidden',next!=='PAUSED');raceComplete.classList.toggle('hidden',next!=='RACE_COMPLETE');shop.classList.add('hidden');gallery.classList.add('hidden');pauseToggle.classList.toggle('hidden',next!=='PLAYING');raceHud.classList.toggle('hidden',!(next==='PLAYING'&&mode==='rally'))}
function resetRivals(){while(racersGroup.children.length){const old=racersGroup.children[0];racersGroup.remove(old);disposeObject(old)}for(let i=0;i<rivals.length;i++){const r=rivals[i];r.row=0;r.x=[-2,2,4][i];r.checkpoint=0;r.crashes=0;r.wait=i*.12;r.finished=false;r.mesh=createCharacter(['RUSTY','BOLT','WISP'][i],.78);r.mesh.position.set(r.x,0,0);racersGroup.add(r.mesh)}}
function start(){clearWorld();biome=save.biome;mode=save.mode;player.row=0;player.x=0;player.moving=null;score=0;furthest=0;forceCrash=false;cameraRow=3;nearMiss={lastRow:-99,count:0};race.finished=false;race.order=[];race.reward=0;race.settled=false;rivalClock=0;simAccumulator=0;ambienceTime=0;pip.position.set(0,0,0);pip.rotation.set(0,Math.PI,0);applyBiome();resetRivals();racersGroup.visible=mode==='rally';ensureWorld(0);ensureMissionDay();if(!save.visited.includes(biome))save.visited.push(biome);if(!save.missions.biomes.includes(biome)){save.missions.biomes.push(biome);addMission('biomes')}else persist();uiDirty=true;setState('PLAYING')}
function targetFor(direction){return{forward:[0,1,Math.PI],back:[0,-1,0],left:[-1,0,-Math.PI/2],right:[1,0,Math.PI/2]}[direction]}
function canOccupy(row,x){if(x<-7||x>7||row<0||row>RACE_LENGTH&&mode==='rally')return false;ensureWorld(row);const l=laneAt(row);return !(l&&(l.blockers.has(x)||(l.type==='water'&&!l.bridges.has(x))))}
function move(direction){if(state!=='PLAYING'||player.moving)return false;const d=targetFor(direction);if(!d)return false;const tx=player.x+d[0],tr=player.row+d[1];if(!canOccupy(tr,tx))return false;player.moving={fromX:player.x,fromRow:player.row,toX:tx,toRow:tr,t:0,angle:d[2]};pip.rotation.y=d[2];playTone(310,.045);return true}
function mintForward(row){if(row<=furthest)return;const gained=row-furthest;furthest=row;score=furthest;changeCoins(gained);addMission('rows',gained);unlockPostcard();if(dailyMode&&mode==='endless')save.records.daily[dateKey()]=Math.max(save.records.daily[dateKey()]||0,score);persist()}
function checkNearMiss(row,x){const l=laneAt(row);if(!l||l.type!=='road'||row-nearMiss.lastRow<4)return;let gap=99;for(const v of vehicles)if(v.row===row)gap=Math.min(gap,Math.abs(v.x-x));if(gap>.78&&gap<1.38){nearMiss.lastRow=row;nearMiss.count++;changeCoins(2);addMission('near');playTone(680,.08)}}
function finishMove(m){player.x=m.toX;player.row=m.toRow;player.moving=null;if(player.row>furthest){mintForward(player.row);checkNearMiss(player.row,player.x);ensureWorld(player.row);if(laneAt(player.row)?.type==='water')addMission('bridges')}if(mode==='rally'&&player.row>=RACE_LENGTH)finishPlayerRace()}
function collideAt(row,x){const l=laneAt(row);if(!l||l.type!=='road')return false;for(const v of vehicles)if(v.row===row&&Math.abs(v.x-x)<(v.width+.56)/2)return true;return false}
function collide(){return forceCrash||(!player.moving&&collideAt(player.row,player.x))}
function unlockPostcard(){if(furthest<10||save.postcards.includes(biome))return false;save.postcards.push(biome);renderGallery();return true}
function die(){if(state!=='PLAYING')return;player.moving=null;unlockPostcard();if(score>best){best=score;save.best=best}persist();setState('GAME_OVER');playTone(95,.22)}
function aiDecision(row,x,profile){const actions=[['forward',row+1,x],['left',row,x-1],['right',row,x+1],['wait',row,x]],risk={careful:4,balanced:2.5,aggressive:1.3}[profile]||2.5;let bestAction='wait',bestScore=-1e9;for(const [a,r,xx] of actions){if(a!=='wait'&&!canOccupy(r,xx))continue;let danger=collideAt(r,xx)?8:0;for(const v of vehicles)if(v.row===r){const predicted=v.x+v.speed*v.direction*.22;danger=Math.max(danger,Math.max(0,1.5-Math.abs(predicted-xx)))}let s=(r-row)*5-Math.abs(xx)*.04-danger*risk+(a==='wait'?.1:0)+seeded(row,profile.length+a.length)*.001;if(s>bestScore){bestScore=s;bestAction=a}}return bestAction}
function crashRival(index){const r=rivals[index];if(!r)return false;r.crashes++;r.row=r.checkpoint;r.x=[-2,2,4][index];r.wait=.65;r.mesh.position.set(r.x,0,-r.row);return true}
function finishRival(r){if(r.finished)return;r.finished=true;race.order.push(r.id);r.mesh.visible=false;if(race.order.length===4)settleRace()}
function finishPlayerRace(){if(race.order.includes(0))return;race.order.push(0);player.moving=null;if(race.order.length===4)settleRace();else{race.finished=true;settleRace()}}
function settleRace(forcedOrder){if(forcedOrder)race.order=forcedOrder.slice();if(race.settled)return;race.settled=true;race.finished=true;const rank=Math.max(1,race.order.indexOf(0)+1),rewards=[60,40,25,15];race.reward=rewards[rank-1];changeCoins(race.reward);save.records.rallyBest=save.records.rallyBest?Math.min(save.records.rallyBest,rank):rank;addMission('rally');unlockPostcard();document.getElementById('race-result').textContent=`PLACE ${rank}/4 · +${race.reward} COINS`;persist();setState('RACE_COMPLETE')}
function updateRivals(dt){rivalClock+=dt;while(rivalClock+1e-9>=RIVAL_STEP){rivalClock-=RIVAL_STEP;for(let i=0;i<rivals.length;i++){const r=rivals[i];if(r.finished)continue;if(r.wait>0){r.wait-=RIVAL_STEP;continue}const a=aiDecision(r.row,r.x,r.profile);if(a==='forward')r.row++;else if(a==='left')r.x--;else if(a==='right')r.x++;else r.wait=.12;if(r.row>=10)r.checkpoint=Math.min(40,Math.floor(r.row/10)*10);if(collideAt(r.row,r.x)){crashRival(i);continue}r.mesh.position.set(r.x,0,-r.row);r.mesh.rotation.y=a==='left'?-Math.PI/2:a==='right'?Math.PI/2:Math.PI;if(r.row>=RACE_LENGTH)finishRival(r)}}}
function updateStep(dt){if(state!=='PLAYING')return;updateAmbience(dt);for(let i=0;i<vehicles.length;i++){const v=vehicles[i];v.x+=v.speed*v.direction*dt;if(v.x>WORLD_HALF+2)v.x=-WORLD_HALF-2;if(v.x<-WORLD_HALF-2)v.x=WORLD_HALF+2;v.mesh.position.x=v.x}if(mode==='rally')updateRivals(dt);if(player.moving){const m=player.moving;m.t+=dt;const p=Math.min(1,m.t/HOP_TIME),smooth=p*p*(3-2*p);pip.position.x=THREE.MathUtils.lerp(m.fromX,m.toX,smooth);pip.position.z=-THREE.MathUtils.lerp(m.fromRow,m.toRow,smooth);pip.position.y=Math.sin(p*Math.PI)*.62;if(p>=1){pip.position.set(m.toX,0,-m.toRow);finishMove(m)}}if(collide())mode==='rally'&&player.row>=10?respawnPlayer():die();cameraRow+=((player.row+3)-cameraRow)*Math.min(1,dt*4.5)}
function update(dt){if(state!=='PLAYING'){simAccumulator=0;return}simAccumulator+=Math.min(Math.max(dt,0),.1);let steps=0;while(simAccumulator+1e-9>=SIM_STEP&&steps<8&&state==='PLAYING'){simAccumulator-=SIM_STEP;updateStep(SIM_STEP);steps++}if(steps)uiDirty=true}
function respawnPlayer(){forceCrash=false;const cp=Math.floor(player.row/10)*10;player.row=cp;player.x=0;player.moving=null;pip.position.set(0,0,-cp);changeCoins(-1);persist()}
function render(t){cameraTarget.set(0,0,-cameraRow);camera.position.set(10,12,10-cameraRow);camera.lookAt(cameraTarget);underlay.position.set(0,-.55,-cameraRow);if(state==='MENU')pip.position.y=Math.sin(t*.002)*.05;renderer.render(scene,camera)}
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);const aspect=w/h,view=12;camera.left=-view*aspect/2;camera.right=view*aspect/2;camera.top=view/2;camera.bottom=-view/2;camera.updateProjectionMatrix();placeSkyDecor()}
function unlockAudio(){if(audio)return;const AC=window.AudioContext||window.webkitAudioContext;if(AC)audio=new AC()}
function playTone(freq,duration){if(!audio||audio.state!=='running')return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='square';osc.frequency.value=freq;gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}
function togglePause(){if(state==='PLAYING')setState('PAUSED');else if(state==='PAUSED')setState('PLAYING')}
function goMenu(){setState('MENU');renderMissions();renderShop();renderGallery()}
function onKey(event){if(event.target instanceof HTMLSelectElement||event.target instanceof HTMLButtonElement)return;const key=event.key.toLowerCase(),dirs={arrowup:'forward',w:'forward',arrowdown:'back',s:'back',arrowleft:'left',a:'left',arrowright:'right',d:'right'};if(dirs[key]){event.preventDefault();move(dirs[key])}else if(key==='p'||key==='escape'){event.preventDefault();togglePause()}else if((key===' '||key==='enter')&&(state==='MENU'||state==='GAME_OVER'||state==='RACE_COMPLETE')){event.preventDefault();unlockAudio();start()}}
let pointerStart=null;function pointerDown(e){if(pointerStart)return;pointerStart={id:e.pointerId,x:e.clientX,y:e.clientY};unlockAudio();if(canvas.setPointerCapture)try{canvas.setPointerCapture(e.pointerId)}catch{}}function clearPointer(e){if(pointerStart&&(e.pointerId===pointerStart.id||e.pointerId===undefined))pointerStart=null}function pointerUp(e){if(!pointerStart||e.pointerId!==pointerStart.id)return;const s=pointerStart;clearPointer(e);if(canvas.releasePointerCapture)try{canvas.releasePointerCapture(e.pointerId)}catch{}const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'back':'forward'))}
addEventListener('keydown',onKey);canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',clearPointer);addEventListener('resize',resize);
document.getElementById('start').addEventListener('click',()=>{unlockAudio();start()});document.getElementById('retry').addEventListener('click',start);document.getElementById('race-retry').addEventListener('click',start);document.getElementById('resume').addEventListener('click',togglePause);pauseToggle.addEventListener('click',togglePause);for(const b of document.querySelectorAll('.menu-return'))b.addEventListener('click',goMenu);document.getElementById('mode-select').addEventListener('change',e=>setMode(e.target.value));document.getElementById('biome-select').addEventListener('change',e=>setBiome(e.target.value));document.getElementById('shop-open').addEventListener('click',()=>{renderShop();menu.classList.add('hidden');shop.classList.remove('hidden')});document.getElementById('shop-close').addEventListener('click',goMenu);document.getElementById('gallery-open').addEventListener('click',()=>{renderGallery();menu.classList.add('hidden');gallery.classList.remove('hidden')});document.getElementById('gallery-close').addEventListener('click',goMenu);document.getElementById('daily-toggle').addEventListener('click',()=>setDailyMode(!dailyMode));
document.getElementById('mode-select').value=mode;document.getElementById('biome-select').value=biome;applyBiome();resize();ensureWorld(0);renderMissions();renderShop();renderGallery();
const game={ready:true,state,THREE_REVISION:THREE.REVISION,scene,camera,renderer,world,ambience,player,pip,lanes,vehicles,rivals,race,save,BIOMES,CHARACTERS,MISSIONS,RACE_LENGTH,dailySeed,nearMiss,start,move,togglePause,setState,setMode,setBiome,buyCharacter,selectCharacter,aiDecision,debug:{advance(seconds){let left=seconds;while(left>0){const step=Math.min(.05,left);update(step);left-=step}},stepSequence(steps){for(const step of steps)update(step)},normalizeSave,ensureMissionDay,changeCoins,uiWriteCount(){return uiWriteCount},blockCell(row,x){ensureWorld(row);laneAt(row).blockers.add(x)},clearBlockers(row){const l=laneAt(row);if(l)l.blockers.clear()},forceCrash(){forceCrash=true},setCoins(n){save.coins=clampInt(n,0,999999);persist()},setRacer(i,row,x){const r=rivals[i];r.row=row;r.x=x;r.checkpoint=Math.floor(row/10)*10;r.mesh.position.set(x,0,-row)},crashRival,finishRace(order){settleRace(order)},setDaily:setDailyMode}};Object.defineProperties(game,{score:{get:()=>score},best:{get:()=>best},biome:{get:()=>biome},mode:{get:()=>mode},character:{get:()=>save.character},dailyMode:{get:()=>dailyMode}});window.__game=game;setState('MENU');updateUI();
function frame(t){const dt=lastTime?Math.min((t-lastTime)/1000,.1):0;lastTime=t;update(dt);if(uiDirty)updateUI();render(t);requestAnimationFrame(frame)}requestAnimationFrame(frame);
